version: 2
jobs:
  build:
    docker:
      - image: rust:1.30.0
    steps:
      - checkout
      - run:
          name: fetch dependencies
          command: cargo fetch
      - run:
          name: build
          command: cargo build
      - run:
          name: test
          command: cargo test
      - run:
          name: lint
          command: |
            rustup component add clippy-preview &&
            cargo clippy
